### ISSUE TITLE
TensorFlow doesn't work and is update available?

### ISSUE THREAD

**Issue by archenroot** [zougloub/gentoo-zougloub-overlay#1]
Hi, I tried your TensorFlow ebuild, but failed on:
no such package '@bazel_tools//tools/cpp': error loading package 'external': Could not load //external package

Do you plan any updated version of this package?

Regards,

Ladislav

**Comment by archenroot** [comment]
I maintain Tensorflow in my overlay and it works now with CUDA 9 and CUDNN 7, I work on supporting more use flags and we plan to merge it into gentoo tree....

**Comment by zougloub** [comment]
Sorry for no response... I'll test your ebuild and hopefully remove mine!
